[images]
remote_images = [
  "^(?:http(?:s)?:\\/\\/i\\.ytimg\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:http(?:s)?:\\/\\/yt3\\.ggpht\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
]

[build]
command = "prisma generate && prisma db push && next build"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps"
PRISMA_SKIP_POSTINSTALL_GENERATE = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
[redirects.query]
url = ":url"
w = ":width"
q = ":quality"
