[build]
  command = "prisma generate && prisma db push && next build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"

# Next.js specific plugin - handles all routing automatically
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
